# Generated by Django 5.2.17 on 2026-08-19 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='uploads/originals/')),
                ('file_type', models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4')], max_length=10)),
                ('target_duration', models.CharField(choices=[('15-30', '15-30 seconds'), ('30-60', '30-60 seconds'), ('60-90', '60-90 seconds')], default='30-60', max_length=10)),
                ('clip_count', models.CharField(choices=[('5', '5 clips'), ('8', '8 clips'), ('12', '12 clips'), ('balanced', 'Balanced')], default='balanced', max_length=10)),
                ('moment_types', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('extracting', 'Extracting Clips'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('why_this_clip', models.TextField()),
                ('hook_strength', models.IntegerField()),
                ('curiosity', models.IntegerField()),
                ('standalone', models.IntegerField()),
                ('value', models.IntegerField()),
                ('entertainment', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('clip_file', models.FileField(blank=True, null=True, upload_to='uploads/clips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='clips.project')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
